<?php
// Include file for SMS interface.

// These variables MUST match your kannel.conf configuration

$bearerboxhost = "127.0.0.1";
define("BEARERBOX_HOST", "127.0.0.1");
define("SENDSMS_PORT",   "14013");
define("ADMIN_PORT",     "14000");
define("ADMIN_PASSWORD", "bar");
define("USERNAME",       "tester");
define("PASSWORD",       "foobar");
define("GLOBAL_SENDER",  "09177355115");
?>
